Install, install.bat

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,12 +12,12 @@ exec 3>"$logfile"
 
 function silent_run
 {
-    eval "$@ >&3 2>&1"
+    eval "$@ >/dev/null 2>&1"
 }
 
 function silent_trun
 {
-    eval "$@ >&3 2>&1 || true"
+    eval "$@ >/dev/null 2>&1 || true"
 }
 
 function do_then_sudo
@@ -26,14 +26,6 @@ function do_then_sudo
     if [ $? != 0 ]; then
         eval "sudo $@"
     fi
-}
-
-function failed
-{
-    echo "FAILED."
-    echo "[_/_] LOG OUTPUT:"
-    cat $logfile
-    exit 1
 }
 
 FILE=liknorm-$VERSION.tar.gz
@@ -45,33 +37,31 @@ silent_trun rm -rf $DIR
 
 echo -n "[1/5] Downloading... "
 silent_run curl -o $FILE -L $URL
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
 
 tar xzf $FILE && cd $DIR
 mkdir build && cd build
 
 echo -n "[2/5] Configuring... "
 silent_run cmake ..
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
 
 echo -n "[3/5] Compiling... "
 silent_run make
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
 
 echo -n "[4/5] Testing... "
 silent_run make test
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
 
 echo -n "[5/5] Installing... "
 silent_run do_then_sudo make install
-[ $? == 0 ] && echo "done." || failed
+[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
 
 cd .. && cd ..
-silent_trun rm liknorm-$VERSION.tar.gz
-silent_trun rm -rf liknorm-$VERSION
+silent_trun rm $FILE
+silent_trun rm -rf $DIR
 
 if type "ldconfig" >/dev/null 2>&1; then
     silent_run do_then_sudo ldconfig
 fi
-
-rm "$logfile" || true
