appveyor 2017, 2015

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,15 +1,20 @@
 #!/bin/bash
 
-VERSION=1.2.9
+VERSION=1.3.0
+
+echo "[_/_] Library(liknorm==$VERSION)"
+
+logfile=$(mktemp /tmp/liknorm.XXXX.log)
+exec 3>"$logfile"
 
 function silent_run
 {
-    eval "$@ >/dev/null 2>&1"
+    eval "$@ >&3 2>&1"
 }
 
 function silent_trun
 {
-    eval "$@ >/dev/null 2>&1 || true"
+    eval "$@ >&3 2>&1 || true"
 }
 
 function do_then_sudo
@@ -18,6 +23,14 @@ function do_then_sudo
     if [ $? != 0 ]; then
         eval "sudo $@"
     fi
+}
+
+function failed
+{
+    echo "FAILED."
+    echo "[_/_] LOG OUTPUT:"
+    cat $logfile
+    exit 1
 }
 
 FILE=liknorm-$VERSION.tar.gz
@@ -29,26 +42,26 @@ silent_trun rm -rf $DIR
 
 echo -n "[1/5] Downloading... "
 silent_run curl -o $FILE -L $URL
-[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+[ $? == 0 ] && echo "done." || failed
 
 tar xzf $FILE && cd $DIR
 mkdir build && cd build
 
 echo -n "[2/5] Configuring... "
 silent_run cmake ..
-[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+[ $? == 0 ] && echo "done." || failed
 
 echo -n "[3/5] Compiling... "
 silent_run make
-[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+[ $? == 0 ] && echo "done." || failed
 
 echo -n "[4/5] Testing... "
 silent_run make test
-[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+[ $? == 0 ] && echo "done." || failed
 
 echo -n "[5/5] Installing... "
 silent_run do_then_sudo make install
-[ $? == 0 ] && echo "done." || { echo "FAILED."; exit 1; }
+[ $? == 0 ] && echo "done." || failed
 
 cd .. && cd ..
 silent_trun rm liknorm-$VERSION.tar.gz
@@ -57,3 +70,5 @@ silent_trun rm -rf liknorm-$VERSION
 if type "ldconfig" >/dev/null 2>&1; then
     silent_run do_then_sudo ldconfig
 fi
+
+rm "$logfile" || true
